/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MFRM.java
 *
 * Created on 02 16, 20, 9:55:27 AM
 */

package arrygrdng;

import javax.swing.JOptionPane;

/**
 *
 * @author user 2
 */
public class MFRM extends javax.swing.JFrame {

    /** Creates new form MFRM */
    public MFRM() {    
        initComponents(); 
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    String names[][]={{"Alvin Morines","Beatriz Robles","Carl Fernandez","Christian Igbaras","Dustin Angelo","Esa Blancaver","Eugene Gelsvison","Ezekiel Lavapiez","Glydel Ilano","Jaimes Robles"},{"James Salingay","Jan Jan","Jasmine Zamboanga","Jheff Jimenez","Jirrymy Pesino","John Santos","John Rick Ledesma","Jomar Pontillas","Kent Ronan","Vice Ganda"},
    {"Theresa Taffalla","Ma Dablo","Meariz Misa","Reginald Soliva","Rex Rodriguez","Reymark Llames","Reil Ballester","Rovic Rodriguez","Shing Villa","Tine Sayson"},
    {"Valdrem Mercene","Vincent Villafuerte","Ace Dante","Aeisha Valencia","Alexis Pelaez","Allena Advincula","Andy Daclitan","Andy Tugay","AnnGie Malicdem","Cammile Aguilar"},
    {"Carla Esguerra","Christian Padayao","Clarisse Orgasan","Cyrill Agarao","Dave Ruedas","Dayne Dela Torre","Ederwheen Romaraog","Edison Canlas","Edmond Ramos","Edwin Enguito"}};
int grad [][][] = new int [4][10][4];
  
   
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lblet = new javax.swing.JLabel();
        lbln = new javax.swing.JLabel();
        lblj = new javax.swing.JLabel();
        lblm = new javax.swing.JLabel();
        lble = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jButton2 = new javax.swing.JButton();
        srch = new javax.swing.JTextField();
        m10 = new javax.swing.JTextField();
        m1 = new javax.swing.JTextField();
        m2 = new javax.swing.JTextField();
        m3 = new javax.swing.JTextField();
        m4 = new javax.swing.JTextField();
        m5 = new javax.swing.JTextField();
        m6 = new javax.swing.JTextField();
        m7 = new javax.swing.JTextField();
        m8 = new javax.swing.JTextField();
        m9 = new javax.swing.JTextField();
        j10 = new javax.swing.JTextField();
        j2 = new javax.swing.JTextField();
        j3 = new javax.swing.JTextField();
        j4 = new javax.swing.JTextField();
        j5 = new javax.swing.JTextField();
        j6 = new javax.swing.JTextField();
        j7 = new javax.swing.JTextField();
        j8 = new javax.swing.JTextField();
        j9 = new javax.swing.JTextField();
        e10 = new javax.swing.JTextField();
        e1 = new javax.swing.JTextField();
        e2 = new javax.swing.JTextField();
        e3 = new javax.swing.JTextField();
        e4 = new javax.swing.JTextField();
        e5 = new javax.swing.JTextField();
        e6 = new javax.swing.JTextField();
        e7 = new javax.swing.JTextField();
        e8 = new javax.swing.JTextField();
        e9 = new javax.swing.JTextField();
        et10 = new javax.swing.JTextField();
        et6 = new javax.swing.JTextField();
        et7 = new javax.swing.JTextField();
        et9 = new javax.swing.JTextField();
        et4 = new javax.swing.JTextField();
        et5 = new javax.swing.JTextField();
        et1 = new javax.swing.JTextField();
        et8 = new javax.swing.JTextField();
        et3 = new javax.swing.JTextField();
        et2 = new javax.swing.JTextField();
        jPanel140 = new javax.swing.JPanel();
        cmb = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        n10 = new javax.swing.JTextField();
        n1 = new javax.swing.JTextField();
        n2 = new javax.swing.JTextField();
        n3 = new javax.swing.JTextField();
        n4 = new javax.swing.JTextField();
        n5 = new javax.swing.JTextField();
        n6 = new javax.swing.JTextField();
        n7 = new javax.swing.JTextField();
        n8 = new javax.swing.JTextField();
        n9 = new javax.swing.JTextField();
        j1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(68, 0, 68));
        jPanel2.setLayout(null);

        jButton1.setBackground(new java.awt.Color(0, 102, 102));
        jButton1.setFont(new java.awt.Font("SansSerif", 0, 14));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("EXIT");
        jButton1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(0, 210, 80, 23);

        jButton3.setBackground(new java.awt.Color(0, 102, 102));
        jButton3.setFont(new java.awt.Font("SansSerif", 0, 14));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("CLEAR");
        jButton3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3);
        jButton3.setBounds(0, 170, 80, 23);

        jButton4.setBackground(new java.awt.Color(0, 102, 102));
        jButton4.setFont(new java.awt.Font("SansSerif", 0, 14));
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("SAVE");
        jButton4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4);
        jButton4.setBounds(0, 130, 80, 23);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 90, 380);

        jPanel3.setBackground(new java.awt.Color(102, 0, 204));
        jPanel3.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Kristen ITC", 1, 12));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ETHICS :");
        jPanel3.add(jLabel1);
        jLabel1.setBounds(610, 10, 80, 17);

        jLabel3.setFont(new java.awt.Font("Kristen ITC", 1, 12));
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("JAVA :");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(250, 10, 70, 17);

        jLabel4.setFont(new java.awt.Font("Kristen ITC", 1, 12));
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("MATH :");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(370, 10, 80, 17);

        jLabel5.setFont(new java.awt.Font("Kristen ITC", 1, 12));
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("ENGLISH :");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(480, 10, 80, 17);

        jLabel12.setFont(new java.awt.Font("Kristen ITC", 1, 12));
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("NAMES :");
        jPanel3.add(jLabel12);
        jLabel12.setBounds(14, 10, 80, 17);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(90, 40, 710, 40);

        jPanel4.setBackground(new java.awt.Color(68, 0, 68));
        jPanel4.setLayout(null);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(null);

        jLabel6.setFont(new java.awt.Font("Kristen ITC", 1, 12));
        jLabel6.setText("ETHICS :");
        jPanel5.add(jLabel6);
        jLabel6.setBounds(690, 10, 80, 17);

        jLabel8.setFont(new java.awt.Font("Kristen ITC", 1, 12));
        jLabel8.setText("JAVA :");
        jPanel5.add(jLabel8);
        jLabel8.setBounds(330, 10, 70, 17);

        jLabel9.setFont(new java.awt.Font("Kristen ITC", 1, 12));
        jLabel9.setText("MATH :");
        jPanel5.add(jLabel9);
        jLabel9.setBounds(450, 10, 80, 17);

        jLabel10.setFont(new java.awt.Font("Kristen ITC", 1, 12));
        jLabel10.setText("ENGLISH :");
        jPanel5.add(jLabel10);
        jLabel10.setBounds(560, 10, 80, 17);

        jLabel11.setFont(new java.awt.Font("Kristen ITC", 1, 12));
        jLabel11.setText("NAME :");
        jPanel5.add(jLabel11);
        jLabel11.setBounds(20, 10, 80, 17);

        jPanel4.add(jPanel5);
        jPanel5.setBounds(10, 70, 780, 40);

        lblet.setFont(new java.awt.Font("Kristen ITC", 0, 18));
        lblet.setForeground(new java.awt.Color(255, 255, 255));
        lblet.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblet.setText("NAMES :");
        jPanel4.add(lblet);
        lblet.setBounds(680, 140, 90, 50);

        lbln.setFont(new java.awt.Font("Kristen ITC", 0, 18));
        lbln.setForeground(new java.awt.Color(255, 255, 255));
        lbln.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbln.setText("NAMES :");
        jPanel4.add(lbln);
        lbln.setBounds(10, 140, 280, 50);

        lblj.setFont(new java.awt.Font("Kristen ITC", 0, 18));
        lblj.setForeground(new java.awt.Color(255, 255, 255));
        lblj.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblj.setText("NAMES :");
        jPanel4.add(lblj);
        lblj.setBounds(320, 140, 90, 50);

        lblm.setFont(new java.awt.Font("Kristen ITC", 0, 18));
        lblm.setForeground(new java.awt.Color(255, 255, 255));
        lblm.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblm.setText("NAMES :");
        jPanel4.add(lblm);
        lblm.setBounds(440, 140, 90, 50);

        lble.setFont(new java.awt.Font("Kristen ITC", 0, 18));
        lble.setForeground(new java.awt.Color(255, 255, 255));
        lble.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lble.setText("NAMES :");
        jPanel4.add(lble);
        lble.setBounds(560, 140, 90, 50);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel4.add(jSeparator1);
        jSeparator1.setBounds(660, 120, 20, 90);

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel4.add(jSeparator2);
        jSeparator2.setBounds(300, 120, 20, 90);

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel4.add(jSeparator3);
        jSeparator3.setBounds(420, 120, 20, 90);

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel4.add(jSeparator4);
        jSeparator4.setBounds(540, 120, 20, 90);

        jButton2.setBackground(new java.awt.Color(0, 102, 102));
        jButton2.setFont(new java.awt.Font("SansSerif", 0, 14));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("SEARCH");
        jButton2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton2);
        jButton2.setBounds(190, 10, 100, 50);

        srch.setFont(new java.awt.Font("Kristen ITC", 0, 15));
        srch.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel4.add(srch);
        srch.setBounds(300, 20, 300, 30);

        jPanel1.add(jPanel4);
        jPanel4.setBounds(0, 400, 800, 270);

        m10.setBackground(new java.awt.Color(51, 0, 102));
        m10.setFont(new java.awt.Font("Kristen ITC", 0, 12));
        m10.setForeground(new java.awt.Color(255, 255, 255));
        m10.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        m10.setCaretColor(new java.awt.Color(255, 255, 255));
        jPanel1.add(m10);
        m10.setBounds(460, 360, 59, 20);

        m1.setFont(new java.awt.Font("Kristen ITC", 0, 12));
        m1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(m1);
        m1.setBounds(460, 90, 59, 20);

        m2.setBackground(new java.awt.Color(51, 0, 102));
        m2.setFont(new java.awt.Font("Kristen ITC", 0, 12));
        m2.setForeground(new java.awt.Color(255, 255, 255));
        m2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        m2.setCaretColor(new java.awt.Color(255, 255, 255));
        jPanel1.add(m2);
        m2.setBounds(460, 120, 59, 20);

        m3.setFont(new java.awt.Font("Kristen ITC", 0, 12));
        m3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(m3);
        m3.setBounds(460, 150, 59, 20);

        m4.setBackground(new java.awt.Color(51, 0, 102));
        m4.setFont(new java.awt.Font("Kristen ITC", 0, 12));
        m4.setForeground(new java.awt.Color(255, 255, 255));
        m4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        m4.setCaretColor(new java.awt.Color(255, 255, 255));
        jPanel1.add(m4);
        m4.setBounds(460, 180, 59, 20);

        m5.setFont(new java.awt.Font("Kristen ITC", 0, 12));
        m5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(m5);
        m5.setBounds(460, 210, 59, 20);

        m6.setBackground(new java.awt.Color(51, 0, 102));
        m6.setFont(new java.awt.Font("Kristen ITC", 0, 12));
        m6.setForeground(new java.awt.Color(255, 255, 255));
        m6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        m6.setCaretColor(new java.awt.Color(255, 255, 255));
        jPanel1.add(m6);
        m6.setBounds(460, 240, 59, 20);

        m7.setFont(new java.awt.Font("Kristen ITC", 0, 12));
        m7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(m7);
        m7.setBounds(460, 270, 59, 20);

        m8.setBackground(new java.awt.Color(51, 0, 102));
        m8.setFont(new java.awt.Font("Kristen ITC", 0, 12));
        m8.setForeground(new java.awt.Color(255, 255, 255));
        m8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        m8.setCaretColor(new java.awt.Color(255, 255, 255));
        jPanel1.add(m8);
        m8.setBounds(460, 300, 59, 20);

        m9.setFont(new java.awt.Font("Kristen ITC", 0, 12));
        m9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(m9);
        m9.setBounds(460, 330, 59, 20);

        j10.setBackground(new java.awt.Color(51, 0, 102));
        j10.setFont(new java.awt.Font("Kristen ITC", 0, 12)); // NOI18N
        j10.setForeground(new java.awt.Color(255, 255, 255));
        j10.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j10.setCaretColor(new java.awt.Color(255, 255, 255));
        jPanel1.add(j10);
        j10.setBounds(340, 360, 59, 20);

        j2.setBackground(new java.awt.Color(51, 0, 102));
        j2.setFont(new java.awt.Font("Kristen ITC", 0, 12));
        j2.setForeground(new java.awt.Color(255, 255, 255));
        j2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j2.setCaretColor(new java.awt.Color(255, 255, 255));
        jPanel1.add(j2);
        j2.setBounds(340, 120, 59, 20);

        j3.setFont(new java.awt.Font("Kristen ITC", 0, 12));
        j3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j3ActionPerformed(evt);
            }
        });
        jPanel1.add(j3);
        j3.setBounds(340, 150, 59, 20);

        j4.setBackground(new java.awt.Color(51, 0, 102));
        j4.setFont(new java.awt.Font("Kristen ITC", 0, 12));
        j4.setForeground(new java.awt.Color(255, 255, 255));
        j4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j4.setCaretColor(new java.awt.Color(255, 255, 255));
        jPanel1.add(j4);
        j4.setBounds(340, 180, 59, 20);

        j5.setFont(new java.awt.Font("Kristen ITC", 0, 12));
        j5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(j5);
        j5.setBounds(340, 210, 59, 20);

        j6.setBackground(new java.awt.Color(51, 0, 102));
        j6.setFont(new java.awt.Font("Kristen ITC", 0, 12));
        j6.setForeground(new java.awt.Color(255, 255, 255));
        j6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j6.setCaretColor(new java.awt.Color(255, 255, 255));
        jPanel1.add(j6);
        j6.setBounds(340, 240, 59, 20);

        j7.setFont(new java.awt.Font("Kristen ITC", 0, 12));
        j7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(j7);
        j7.setBounds(340, 270, 59, 20);

        j8.setBackground(new java.awt.Color(51, 0, 102));
        j8.setFont(new java.awt.Font("Kristen ITC", 0, 12));
        j8.setForeground(new java.awt.Color(255, 255, 255));
        j8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j8.setCaretColor(new java.awt.Color(255, 255, 255));
        jPanel1.add(j8);
        j8.setBounds(340, 300, 59, 20);

        j9.setFont(new java.awt.Font("Kristen ITC", 0, 12));
        j9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(j9);
        j9.setBounds(340, 330, 59, 20);

        e10.setBackground(new java.awt.Color(51, 0, 102));
        e10.setFont(new java.awt.Font("Kristen ITC", 0, 12)); // NOI18N
        e10.setForeground(new java.awt.Color(255, 255, 255));
        e10.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        e10.setCaretColor(new java.awt.Color(255, 255, 255));
        jPanel1.add(e10);
        e10.setBounds(580, 360, 59, 20);

        e1.setFont(new java.awt.Font("Kristen ITC", 0, 12));
        e1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(e1);
        e1.setBounds(580, 90, 59, 20);

        e2.setBackground(new java.awt.Color(51, 0, 102));
        e2.setFont(new java.awt.Font("Kristen ITC", 0, 12));
        e2.setForeground(new java.awt.Color(255, 255, 255));
        e2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        e2.setCaretColor(new java.awt.Color(255, 255, 255));
        jPanel1.add(e2);
        e2.setBounds(580, 120, 59, 20);

        e3.setFont(new java.awt.Font("Kristen ITC", 0, 12));
        e3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(e3);
        e3.setBounds(580, 150, 59, 20);

        e4.setBackground(new java.awt.Color(51, 0, 102));
        e4.setFont(new java.awt.Font("Kristen ITC", 0, 12));
        e4.setForeground(new java.awt.Color(255, 255, 255));
        e4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        e4.setCaretColor(new java.awt.Color(255, 255, 255));
        e4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                e4ActionPerformed(evt);
            }
        });
        jPanel1.add(e4);
        e4.setBounds(580, 180, 59, 20);

        e5.setFont(new java.awt.Font("Kristen ITC", 0, 12));
        e5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(e5);
        e5.setBounds(580, 210, 59, 20);

        e6.setBackground(new java.awt.Color(51, 0, 102));
        e6.setFont(new java.awt.Font("Kristen ITC", 0, 12));
        e6.setForeground(new java.awt.Color(255, 255, 255));
        e6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        e6.setCaretColor(new java.awt.Color(255, 255, 255));
        jPanel1.add(e6);
        e6.setBounds(580, 240, 59, 20);

        e7.setFont(new java.awt.Font("Kristen ITC", 0, 12));
        e7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(e7);
        e7.setBounds(580, 270, 59, 20);

        e8.setBackground(new java.awt.Color(51, 0, 102));
        e8.setFont(new java.awt.Font("Kristen ITC", 0, 12));
        e8.setForeground(new java.awt.Color(255, 255, 255));
        e8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        e8.setCaretColor(new java.awt.Color(255, 255, 255));
        jPanel1.add(e8);
        e8.setBounds(580, 300, 59, 20);

        e9.setFont(new java.awt.Font("Kristen ITC", 0, 12));
        e9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(e9);
        e9.setBounds(580, 330, 59, 20);

        et10.setBackground(new java.awt.Color(51, 0, 102));
        et10.setFont(new java.awt.Font("Kristen ITC", 0, 12));
        et10.setForeground(new java.awt.Color(255, 255, 255));
        et10.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        et10.setCaretColor(new java.awt.Color(255, 255, 255));
        jPanel1.add(et10);
        et10.setBounds(700, 360, 59, 20);

        et6.setBackground(new java.awt.Color(51, 0, 102));
        et6.setFont(new java.awt.Font("Kristen ITC", 0, 12));
        et6.setForeground(new java.awt.Color(255, 255, 255));
        et6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        et6.setCaretColor(new java.awt.Color(255, 255, 255));
        jPanel1.add(et6);
        et6.setBounds(700, 240, 59, 20);

        et7.setFont(new java.awt.Font("Kristen ITC", 0, 12));
        et7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(et7);
        et7.setBounds(700, 270, 59, 20);

        et9.setFont(new java.awt.Font("Kristen ITC", 0, 12));
        et9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(et9);
        et9.setBounds(700, 330, 59, 20);

        et4.setBackground(new java.awt.Color(51, 0, 102));
        et4.setFont(new java.awt.Font("Kristen ITC", 0, 12));
        et4.setForeground(new java.awt.Color(255, 255, 255));
        et4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        et4.setCaretColor(new java.awt.Color(255, 255, 255));
        jPanel1.add(et4);
        et4.setBounds(700, 180, 59, 20);

        et5.setFont(new java.awt.Font("Kristen ITC", 0, 12));
        et5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(et5);
        et5.setBounds(700, 210, 59, 20);

        et1.setFont(new java.awt.Font("Kristen ITC", 0, 12));
        et1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(et1);
        et1.setBounds(700, 90, 59, 20);

        et8.setBackground(new java.awt.Color(51, 0, 102));
        et8.setFont(new java.awt.Font("Kristen ITC", 0, 12));
        et8.setForeground(new java.awt.Color(255, 255, 255));
        et8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        et8.setCaretColor(new java.awt.Color(255, 255, 255));
        jPanel1.add(et8);
        et8.setBounds(700, 300, 59, 20);

        et3.setFont(new java.awt.Font("Kristen ITC", 0, 12));
        et3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(et3);
        et3.setBounds(700, 150, 59, 20);

        et2.setBackground(new java.awt.Color(51, 0, 102));
        et2.setFont(new java.awt.Font("Kristen ITC", 0, 12));
        et2.setForeground(new java.awt.Color(255, 255, 255));
        et2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        et2.setCaretColor(new java.awt.Color(255, 255, 255));
        jPanel1.add(et2);
        et2.setBounds(700, 120, 59, 20);

        jPanel140.setBackground(new java.awt.Color(102, 0, 204));
        jPanel140.setLayout(null);

        cmb.setFont(new java.awt.Font("Kristen ITC", 1, 18));
        cmb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Please Select Section", "BSIS1", "BSIS2", "BSIS3", " ", " ", " " }));
        cmb.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        cmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbActionPerformed(evt);
            }
        });
        jPanel140.add(cmb);
        cmb.setBounds(110, 0, 240, 30);

        jLabel2.setFont(new java.awt.Font("Kristen ITC", 1, 12));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("SECTION :");
        jPanel140.add(jLabel2);
        jLabel2.setBounds(10, 0, 90, 30);

        jPanel1.add(jPanel140);
        jPanel140.setBounds(90, 0, 350, 30);

        n10.setBackground(new java.awt.Color(51, 0, 102));
        n10.setEditable(false);
        n10.setFont(new java.awt.Font("Kristen ITC", 0, 12));
        n10.setForeground(new java.awt.Color(255, 255, 255));
        n10.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(n10);
        n10.setBounds(100, 360, 220, 20);

        n1.setEditable(false);
        n1.setFont(new java.awt.Font("Kristen ITC", 0, 12));
        n1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(n1);
        n1.setBounds(100, 90, 220, 20);

        n2.setBackground(new java.awt.Color(51, 0, 102));
        n2.setEditable(false);
        n2.setFont(new java.awt.Font("Kristen ITC", 0, 12));
        n2.setForeground(new java.awt.Color(255, 255, 255));
        n2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(n2);
        n2.setBounds(100, 120, 220, 20);

        n3.setEditable(false);
        n3.setFont(new java.awt.Font("Kristen ITC", 0, 12));
        n3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        n3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n3ActionPerformed(evt);
            }
        });
        jPanel1.add(n3);
        n3.setBounds(100, 150, 220, 20);

        n4.setBackground(new java.awt.Color(51, 0, 102));
        n4.setEditable(false);
        n4.setFont(new java.awt.Font("Kristen ITC", 0, 12));
        n4.setForeground(new java.awt.Color(255, 255, 255));
        n4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(n4);
        n4.setBounds(100, 180, 220, 20);

        n5.setEditable(false);
        n5.setFont(new java.awt.Font("Kristen ITC", 0, 12));
        n5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(n5);
        n5.setBounds(100, 210, 220, 20);

        n6.setBackground(new java.awt.Color(51, 0, 102));
        n6.setEditable(false);
        n6.setFont(new java.awt.Font("Kristen ITC", 0, 12));
        n6.setForeground(new java.awt.Color(255, 255, 255));
        n6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(n6);
        n6.setBounds(100, 240, 220, 20);

        n7.setEditable(false);
        n7.setFont(new java.awt.Font("Kristen ITC", 0, 12));
        n7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(n7);
        n7.setBounds(100, 270, 220, 20);

        n8.setBackground(new java.awt.Color(51, 0, 102));
        n8.setEditable(false);
        n8.setFont(new java.awt.Font("Kristen ITC", 0, 12));
        n8.setForeground(new java.awt.Color(255, 255, 255));
        n8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(n8);
        n8.setBounds(100, 300, 220, 20);

        n9.setEditable(false);
        n9.setFont(new java.awt.Font("Kristen ITC", 0, 12));
        n9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(n9);
        n9.setBounds(100, 330, 220, 20);

        j1.setFont(new java.awt.Font("Kristen ITC", 0, 12));
        j1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(j1);
        j1.setBounds(340, 90, 59, 20);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 800, 740);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-815)/2, (screenSize.height-714)/2, 815, 714);
    }// </editor-fold>//GEN-END:initComponents

    private void j3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j3ActionPerformed

    private void n3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_n3ActionPerformed

    private void cmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbActionPerformed
String cb= (String)cmb.getSelectedItem();

if(cb=="BSIS1"){
    n1.setText(names[0][0]);
    n2.setText(names[0][1]);
    n3.setText(names[0][2]);
    n4.setText(names[0][3]);
    n5.setText(names[0][4]);
    n6.setText(names[0][5]);
    n7.setText(names[0][6]);
    n8.setText(names[0][7]);
    n9.setText(names[0][8]);
    n10.setText(names[0][9]);

}
if(cb=="BSIS2"){
     n1.setText(names[1][0]);
    n2.setText(names[1][1]);
    n3.setText(names[1][2]);
    n4.setText(names[1][3]);
    n5.setText(names[1][4]);
    n6.setText(names[1][5]);
    n7.setText(names[1][6]);
    n8.setText(names[1][7]);
    n9.setText(names[1][8]);
    n10.setText(names[1][9]);

}
if(cb=="BSIS3"){
      n1.setText(names[2][0]);
    n2.setText(names[2][1]);
    n3.setText(names[2][2]);
    n4.setText(names[2][3]);
    n5.setText(names[2][4]);
    n6.setText(names[2][5]);
    n7.setText(names[2][6]);
    n8.setText(names[2][7]);
    n9.setText(names[2][8]);
    n10.setText(names[2][9]);
}

    }//GEN-LAST:event_cmbActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
try{
    if(cmb.getSelectedItem()=="BSIS1"){
      grad[0][0][0]=Integer.parseInt(j1.getText());
      grad[0][1][0]=Integer.parseInt(j2.getText());
      grad[0][2][0]=Integer.parseInt(j3.getText());
      grad[0][3][0]=Integer.parseInt(j4.getText());
      grad[0][4][0]=Integer.parseInt(j5.getText());
      grad[0][5][0]=Integer.parseInt(j6.getText());
      grad[0][6][0]=Integer.parseInt(j7.getText());
      grad[0][7][0]=Integer.parseInt(j8.getText());
      grad[0][8][0]=Integer.parseInt(j9.getText());
      grad[0][9][0]=Integer.parseInt(j10.getText());

       grad[0][0][1]=Integer.parseInt(m1.getText());
      grad[0][1][1]=Integer.parseInt(m2.getText());
      grad[0][2][1]=Integer.parseInt(m3.getText());
      grad[0][3][1]=Integer.parseInt(m4.getText());
      grad[0][4][1]=Integer.parseInt(m5.getText());
      grad[0][5][1]=Integer.parseInt(m6.getText());
      grad[0][6][1]=Integer.parseInt(m7.getText());
      grad[0][7][1]=Integer.parseInt(m8.getText());
      grad[0][8][1]=Integer.parseInt(m9.getText());
      grad[0][9][1]=Integer.parseInt(m10.getText());

       grad[0][0][2]=Integer.parseInt(e1.getText());
      grad[0][1][2]=Integer.parseInt(e2.getText());
      grad[0][2][2]=Integer.parseInt(e3.getText());
      grad[0][3][2]=Integer.parseInt(e4.getText());
      grad[0][4][2]=Integer.parseInt(e5.getText());
      grad[0][5][2]=Integer.parseInt(e6.getText());
      grad[0][6][2]=Integer.parseInt(e7.getText());
      grad[0][7][2]=Integer.parseInt(e8.getText());
      grad[0][8][2]=Integer.parseInt(e9.getText());
      grad[0][9][2]=Integer.parseInt(e10.getText());

       grad[0][0][3]=Integer.parseInt(et1.getText());
      grad[0][1][3]=Integer.parseInt(et2.getText());
      grad[0][2][3]=Integer.parseInt(et3.getText());
      grad[0][3][3]=Integer.parseInt(et4.getText());
      grad[0][4][3]=Integer.parseInt(et5.getText());
      grad[0][5][3]=Integer.parseInt(et6.getText());
      grad[0][6][3]=Integer.parseInt(et7.getText());
      grad[0][7][3]=Integer.parseInt(et8.getText());
      grad[0][8][3]=Integer.parseInt(et9.getText());
      grad[0][9][3]=Integer.parseInt(et10.getText());


    }
    if(cmb.getSelectedItem()=="BSIS2"){
      grad[1][0][0]=Integer.parseInt(j1.getText());
      grad[1][1][0]=Integer.parseInt(j2.getText());
      grad[1][2][0]=Integer.parseInt(j3.getText());
      grad[1][3][0]=Integer.parseInt(j4.getText());
      grad[1][4][0]=Integer.parseInt(j5.getText());
      grad[1][5][0]=Integer.parseInt(j6.getText());
      grad[1][6][0]=Integer.parseInt(j7.getText());
      grad[1][7][0]=Integer.parseInt(j8.getText());
      grad[1][8][0]=Integer.parseInt(j9.getText());
      grad[1][9][0]=Integer.parseInt(j10.getText());

      grad[1][0][1]=Integer.parseInt(m1.getText());
      grad[1][1][1]=Integer.parseInt(m2.getText());
      grad[1][2][1]=Integer.parseInt(m3.getText());
      grad[1][3][1]=Integer.parseInt(m4.getText());
      grad[1][4][1]=Integer.parseInt(m5.getText());
      grad[1][5][1]=Integer.parseInt(m6.getText());
      grad[1][6][1]=Integer.parseInt(m7.getText());
      grad[1][7][1]=Integer.parseInt(m8.getText());
      grad[1][8][1]=Integer.parseInt(m9.getText());
      grad[1][9][1]=Integer.parseInt(m10.getText());

      grad[1][0][2]=Integer.parseInt(e1.getText());
      grad[1][1][2]=Integer.parseInt(e2.getText());
      grad[1][2][2]=Integer.parseInt(e3.getText());
      grad[1][3][2]=Integer.parseInt(e4.getText());
      grad[1][4][2]=Integer.parseInt(e5.getText());
      grad[1][5][2]=Integer.parseInt(e6.getText());
      grad[1][6][2]=Integer.parseInt(e7.getText());
      grad[1][7][2]=Integer.parseInt(e8.getText());
      grad[1][8][2]=Integer.parseInt(e9.getText());
      grad[1][9][2]=Integer.parseInt(e10.getText());

      grad[1][0][3]=Integer.parseInt(et1.getText());
      grad[1][1][3]=Integer.parseInt(et2.getText());
      grad[1][2][3]=Integer.parseInt(et3.getText());
      grad[1][3][3]=Integer.parseInt(et4.getText());
      grad[1][4][3]=Integer.parseInt(et5.getText());
      grad[1][5][3]=Integer.parseInt(et6.getText());
      grad[1][6][3]=Integer.parseInt(et7.getText());
      grad[1][7][3]=Integer.parseInt(et8.getText());
      grad[1][8][3]=Integer.parseInt(et9.getText());
      grad[1][9][3]=Integer.parseInt(et10.getText());


    }
      if(cmb.getSelectedItem()=="BSIS3"){
      grad[2][0][0]=Integer.parseInt(j1.getText());
      grad[2][1][0]=Integer.parseInt(j2.getText());
      grad[2][2][0]=Integer.parseInt(j3.getText());
      grad[2][3][0]=Integer.parseInt(j4.getText());
      grad[2][4][0]=Integer.parseInt(j5.getText());
      grad[2][5][0]=Integer.parseInt(j6.getText());
      grad[2][6][0]=Integer.parseInt(j7.getText());
      grad[2][7][0]=Integer.parseInt(j8.getText());
      grad[2][8][0]=Integer.parseInt(j9.getText());
      grad[2][9][0]=Integer.parseInt(j10.getText());

      grad[2][0][1]=Integer.parseInt(m1.getText());
      grad[2][1][1]=Integer.parseInt(m2.getText());
      grad[2][2][1]=Integer.parseInt(m3.getText());
      grad[2][3][1]=Integer.parseInt(m4.getText());
      grad[2][4][1]=Integer.parseInt(m5.getText());
      grad[2][5][1]=Integer.parseInt(m6.getText());
      grad[2][6][1]=Integer.parseInt(m7.getText());
      grad[2][7][1]=Integer.parseInt(m8.getText());
      grad[2][8][1]=Integer.parseInt(m9.getText());
      grad[2][9][1]=Integer.parseInt(m10.getText());

      grad[2][0][2]=Integer.parseInt(e1.getText());
      grad[2][1][2]=Integer.parseInt(e2.getText());
      grad[2][2][2]=Integer.parseInt(e3.getText());
      grad[2][3][2]=Integer.parseInt(e4.getText());
      grad[2][4][2]=Integer.parseInt(e5.getText());
      grad[2][5][2]=Integer.parseInt(e6.getText());
      grad[2][6][2]=Integer.parseInt(e7.getText());
      grad[2][7][2]=Integer.parseInt(e8.getText());
      grad[2][8][2]=Integer.parseInt(e9.getText());
      grad[2][9][2]=Integer.parseInt(e10.getText());

      grad[2][0][3]=Integer.parseInt(et1.getText());
      grad[2][1][3]=Integer.parseInt(et2.getText());
      grad[2][2][3]=Integer.parseInt(et3.getText());
      grad[2][3][3]=Integer.parseInt(et4.getText());
      grad[2][4][3]=Integer.parseInt(et5.getText());
      grad[2][5][3]=Integer.parseInt(et6.getText());
      grad[2][6][3]=Integer.parseInt(et7.getText());
      grad[2][7][3]=Integer.parseInt(et8.getText());
      grad[2][8][3]=Integer.parseInt(et9.getText());
      grad[2][9][3]=Integer.parseInt(et10.getText());


      }
      
      JOptionPane.showMessageDialog(null,"SUCCESSFULLY SAVED!");
} catch(Exception e){
        JOptionPane.showMessageDialog(null,"Please fill all the Grades");
      }

    }//GEN-LAST:event_jButton4ActionPerformed

    private void e4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_e4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_e4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
   n1.setText("");
   n2.setText("");
   n3.setText("");
   n4.setText("");
   n5.setText("");
   n6.setText("");
   n7.setText("");
   n8.setText("");
   n9.setText("");
   n10.setText("");

   j1.setText("");
   j2.setText("");
   j3.setText("");
   j4.setText("");
   j5.setText("");
   j6.setText("");
   j7.setText("");
   j8.setText("");
   j9.setText("");
   j10.setText("");

   m1.setText("");
   m2.setText("");
   m3.setText("");
   m4.setText("");
   m5.setText("");
   m6.setText("");
   m7.setText("");
   m8.setText("");
   m9.setText("");
   m10.setText("");

   e1.setText("");
   e2.setText("");
   e3.setText("");
   e4.setText("");
   e5.setText("");
   e6.setText("");
   e7.setText("");
   e8.setText("");
   e9.setText("");
   e10.setText("");

   et1.setText("");
   et2.setText("");
   et3.setText("");
   et4.setText("");
   et5.setText("");
   et6.setText("");
   et7.setText("");
   et8.setText("");
   et9.setText("");
   et10.setText("");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      if(JOptionPane.showConfirmDialog(null,"Are you sure you want to quit?","EXIT",JOptionPane.YES_NO_OPTION)==JOptionPane.YES_NO_OPTION){
          System.exit(0);
      }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
     try{
if(srch.getText().equalsIgnoreCase(names[0][0])){
    lbln.setText(names[0][0]);
    lblj.setText(Integer.toString(grad[0][0][0]));
    lblm.setText(Integer.toString(grad[0][0][1]));
    lble.setText(Integer.toString(grad[0][0][2]));
    lblet.setText(Integer.toString(grad[0][0][3]));
    
}
if(srch.getText().equalsIgnoreCase(names[0][1])){
    lbln.setText(names[0][1]);
    lblj.setText(Integer.toString(grad[0][1][0]));
    lblm.setText(Integer.toString(grad[0][1][1]));
    lble.setText(Integer.toString(grad[0][1][2]));
    lblet.setText(Integer.toString(grad[0][1][3]));
}
if(srch.getText().equalsIgnoreCase(names[0][2])){
    lbln.setText(names[0][2]);
    lblj.setText(Integer.toString(grad[0][2][0]));
    lblm.setText(Integer.toString(grad[0][2][1]));
    lble.setText(Integer.toString(grad[0][2][2]));
    lblet.setText(Integer.toString(grad[0][2][3]));
}
if(srch.getText().equalsIgnoreCase(names[0][3])){
    lbln.setText(names[0][3]);
    lblj.setText(Integer.toString(grad[0][3][0]));
    lblm.setText(Integer.toString(grad[0][3][1]));
    lble.setText(Integer.toString(grad[0][3][2]));
    lblet.setText(Integer.toString(grad[0][3][3]));
}
if(srch.getText().equalsIgnoreCase(names[0][4])){
    lbln.setText(names[0][4]);
    lblj.setText(Integer.toString(grad[0][4][0]));
    lblm.setText(Integer.toString(grad[0][4][1]));
    lble.setText(Integer.toString(grad[0][4][2]));
    lblet.setText(Integer.toString(grad[0][4][3]));
}
if(srch.getText().equalsIgnoreCase(names[0][5])){
    lbln.setText(names[0][5]);
    lblj.setText(Integer.toString(grad[0][5][0]));
    lblm.setText(Integer.toString(grad[0][5][1]));
    lble.setText(Integer.toString(grad[0][5][2]));
   lblet.setText(Integer.toString(grad[0][5][3]));
}
if(srch.getText().equalsIgnoreCase(names[0][6])){
    lbln.setText(names[0][6]);
    lblj.setText(Integer.toString(grad[0][6][0]));
    lblm.setText(Integer.toString(grad[0][6][1]));
    lble.setText(Integer.toString(grad[0][6][2]));
    lblet.setText(Integer.toString(grad[0][6][3]));
}
if(srch.getText().equalsIgnoreCase(names[0][7])){
    lbln.setText(names[0][7]);
    lblj.setText(Integer.toString(grad[0][7][0]));
    lblm.setText(Integer.toString(grad[0][7][1]));
    lble.setText(Integer.toString(grad[0][7][2]));
    lblet.setText(Integer.toString(grad[0][7][3]));
}
if(srch.getText().equalsIgnoreCase(names[0][8])){
    lbln.setText(names[0][8]);
    lblj.setText(Integer.toString(grad[0][8][0]));
    lblm.setText(Integer.toString(grad[0][8][1]));
    lble.setText(Integer.toString(grad[0][8][2]));
    lblet.setText(Integer.toString(grad[0][8][3]));
}
if(srch.getText().equalsIgnoreCase(names[0][9])){
    lbln.setText(names[0][9]);
    lblj.setText(Integer.toString(grad[0][9][0]));
    lblm.setText(Integer.toString(grad[0][9][1]));
    lble.setText(Integer.toString(grad[0][9][2]));
    lblet.setText(Integer.toString(grad[0][9][3]));
}


if(srch.getText().equalsIgnoreCase(names[1][0])){
    lbln.setText(names[1][0]);
    lblj.setText(Integer.toString(grad[1][0][0]));
    lblm.setText(Integer.toString(grad[1][0][1]));
    lble.setText(Integer.toString(grad[1][0][2]));
    lblet.setText(Integer.toString(grad[1][0][3]));
}
if(srch.getText().equalsIgnoreCase(names[1][1])){
    lbln.setText(names[1][1]);
    lblj.setText(Integer.toString(grad[1][1][0]));
    lblm.setText(Integer.toString(grad[1][1][1]));
    lble.setText(Integer.toString(grad[1][1][2]));
    lblet.setText(Integer.toString(grad[1][1][3]));
}
if(srch.getText().equalsIgnoreCase(names[1][2])){
    lbln.setText(names[1][2]);
    lblj.setText(Integer.toString(grad[1][2][0]));
    lblm.setText(Integer.toString(grad[1][2][1]));
    lble.setText(Integer.toString(grad[1][2][2]));
    lblet.setText(Integer.toString(grad[1][2][3]));
}
if(srch.getText().equalsIgnoreCase(names[1][3])){
    lbln.setText(names[1][3]);
    lblj.setText(Integer.toString(grad[1][3][0]));
    lblm.setText(Integer.toString(grad[1][3][1]));
    lble.setText(Integer.toString(grad[1][3][2]));
    lblet.setText(Integer.toString(grad[1][3][3]));
}
if(srch.getText().equalsIgnoreCase(names[1][4])){
    lbln.setText(names[1][4]);
    lblj.setText(Integer.toString(grad[1][4][0]));
    lblm.setText(Integer.toString(grad[1][4][1]));
    lble.setText(Integer.toString(grad[1][4][2]));
    lblet.setText(Integer.toString(grad[1][4][3]));
}
if(srch.getText().equalsIgnoreCase(names[1][5])){
    lbln.setText(names[1][5]);
    lblj.setText(Integer.toString(grad[1][5][0]));
    lblm.setText(Integer.toString(grad[1][5][1]));
    lble.setText(Integer.toString(grad[1][5][2]));
    lblet.setText(Integer.toString(grad[1][5][3]));
}
if(srch.getText().equalsIgnoreCase(names[1][6])){
    lbln.setText(names[1][6]);
    lblj.setText(Integer.toString(grad[1][6][0]));
    lblm.setText(Integer.toString(grad[1][6][1]));
    lble.setText(Integer.toString(grad[1][6][2]));
    lblet.setText(Integer.toString(grad[1][6][3]));
}
if(srch.getText().equalsIgnoreCase(names[1][7])){
    lbln.setText(names[1][7]);
    lblj.setText(Integer.toString(grad[1][7][0]));
    lblm.setText(Integer.toString(grad[1][7][1]));
    lble.setText(Integer.toString(grad[1][7][2]));
    lblet.setText(Integer.toString(grad[1][7][3]));
}
if(srch.getText().equalsIgnoreCase(names[1][8])){
    lbln.setText(names[1][8]);
    lblj.setText(Integer.toString(grad[1][8][0]));
    lblm.setText(Integer.toString(grad[1][8][1]));
    lble.setText(Integer.toString(grad[1][8][2]));
    lblet.setText(Integer.toString(grad[1][8][3]));
}
if(srch.getText().equalsIgnoreCase(names[1][9])){
    lbln.setText(names[1][9]);
    lblj.setText(Integer.toString(grad[1][9][1]));
    lblm.setText(Integer.toString(grad[1][9][1]));
    lble.setText(Integer.toString(grad[1][9][2]));
    lblet.setText(Integer.toString(grad[1][9][3]));
}


if(srch.getText().equalsIgnoreCase(names[2][0])){
    lbln.setText(names[2][0]);
    lblj.setText(Integer.toString(grad[2][0][0]));
    lblm.setText(Integer.toString(grad[2][0][1]));
    lble.setText(Integer.toString(grad[2][0][2]));
    lblet.setText(Integer.toString(grad[2][0][3]));

}
if(srch.getText().equalsIgnoreCase(names[2][1])){
    lbln.setText(names[2][1]);
    lblj.setText(Integer.toString(grad[2][2][0]));
    lblm.setText(Integer.toString(grad[2][2][1]));
    lble.setText(Integer.toString(grad[2][2][2]));
    lblet.setText(Integer.toString(grad[2][2][3]));
}
if(srch.getText().equalsIgnoreCase(names[2][2])){
    lbln.setText(names[2][2]);
    lblj.setText(Integer.toString(grad[2][2][0]));
    lblm.setText(Integer.toString(grad[2][2][1]));
    lble.setText(Integer.toString(grad[2][2][2]));
    lblet.setText(Integer.toString(grad[2][2][3]));
}
if(srch.getText().equalsIgnoreCase(names[2][3])){
    lbln.setText(names[2][3]);
    lblj.setText(Integer.toString(grad[2][3][0]));
    lblm.setText(Integer.toString(grad[2][3][1]));
    lble.setText(Integer.toString(grad[2][3][2]));
    lblet.setText(Integer.toString(grad[2][3][3]));
}
if(srch.getText().equalsIgnoreCase(names[2][4])){
    lbln.setText(names[2][4]);
    lblj.setText(Integer.toString(grad[2][4][0]));
    lblm.setText(Integer.toString(grad[2][4][1]));
    lble.setText(Integer.toString(grad[2][4][2]));
    lblet.setText(Integer.toString(grad[2][4][3]));
}
if(srch.getText().equalsIgnoreCase(names[2][5])){
    lbln.setText(names[2][5]);
    lblj.setText(Integer.toString(grad[2][5][0]));
    lblm.setText(Integer.toString(grad[2][5][1]));
    lble.setText(Integer.toString(grad[2][5][2]));
    lblet.setText(Integer.toString(grad[2][5][3]));
}
if(srch.getText().equals(names[2][6])){
    lbln.setText(names[2][6]);
    lblj.setText(Integer.toString(grad[2][6][0]));
    lblm.setText(Integer.toString(grad[2][6][1]));
    lble.setText(Integer.toString(grad[2][6][2]));
    lblet.setText(Integer.toString(grad[2][6][3]));
}
if(srch.getText().equalsIgnoreCase(names[2][7])){
    lbln.setText(names[2][7]);
    lblj.setText(Integer.toString(grad[2][7][0]));
    lblm.setText(Integer.toString(grad[2][7][1]));
    lble.setText(Integer.toString(grad[2][7][2]));
    lblet.setText(Integer.toString(grad[2][7][3]));
}
if(srch.getText().equalsIgnoreCase(names[2][8])){
    lbln.setText(names[2][8]);
    lblj.setText(Integer.toString(grad[2][8][0]));
    lblm.setText(Integer.toString(grad[2][8][1]));
    lble.setText(Integer.toString(grad[2][8][2]));
    lblet.setText(Integer.toString(grad[2][8][3]));
}
if(srch.getText().equalsIgnoreCase(names[2][9])){
    lbln.setText(names[2][9]);
    lblj.setText(Integer.toString(grad[2][9][0]));
    lblm.setText(Integer.toString(grad[2][9][1]));
    lble.setText(Integer.toString(grad[2][9][2]));
    lblet.setText(Integer.toString(grad[2][9][3]));
}




String javs = lblj.getText();
int ja=Integer.parseInt(javs);
String mats=lblm.getText();
int ma=Integer.parseInt(mats);
String eng = lble.getText();
int en=Integer.parseInt(eng);
String eth= lblet.getText();
int et=Integer.parseInt(eth);

if(ja==98||ja==99||ja==100){
    lblj.setText("1.00");
        }
if(ja==95||ja==96||ja==97){
    lblj.setText("1.25");
        }
if(ja==92||ja==93||ja==94){
    lblj.setText("1.50");
       }
if(ja==89||ja==90||ja==91){
    lblj.setText("1.75");
        }
if(ja==86||ja==87||ja==88){
    lblj.setText("2.00");
        }
if(ja==86||ja==85){
    lblj.setText("2.25");
        }
if(ja==80||ja==82){
    lblj.setText("2.50");
        }
if(ja==77||ja==78||ja==79){
    lblj.setText("2.75");
        }
if(ja==75||ja==76){
     lblj.setText("3.00");
        }
if(ja==75||ja==74||ja==73||ja==72||ja==71||ja==70||ja==69||ja==68||ja==67||ja==66||ja==65||ja==64||ja==63||ja==62||ja==61||ja==60||ja==59){
    lblj.setText("5.00");
        }


if(ma==98||ma==99||ma==100){
    lblm.setText("1.00");
        }
if(ma==95||ma==96||ma==97){
    lblm.setText("1.25");
        }
if(ma==92||ma==93||ma==94){
    lblm.setText("1.50");
       }
if(ma==89||ma==90||ma==91){
    lblm.setText("1.75");
        }
if(ma==86||ma==87||ma==88){
    lblm.setText("2.00");
        }
if(ma==86||ma==85){
    lblm.setText("2.25");
        }
if(ma==80||ma==82){
    lblm.setText("2.50");
        }
if(ma==77||ma==78||ma==79){
    lblm.setText("2.75");
        }
if(ma==75||ma==76){
     lblm.setText("3.00");
        }
if(ma==75||ma==74||ma==73||ma==72||ma==71||ma==70||ma==69||ma==68||ma==67||ma==66||ma==65||ma==64||ma==63||ma==62||ma==61||ma==60||ma==59){
    lblm.setText("5.00");
        }
       
        
if(en==98||en==99||en==100){
    lble.setText("1.00");
        }
if(en==95||en==96||en==97){
    lble.setText("1.25");
       }
if(en==92||en==93||en==94){
    lble.setText("1.50");
       }
if(en==89||en==90||en==91){
    lble.setText("1.75");
        }
if(en==86||en==87||en==88){
    lble.setText("2.00");
        }
if(en==86||en==85){
    lble.setText("2.25");
        }
if(en==80||en==82){
    lble.setText("2.50");
        }
if(en==77||en==78||en==79){
    lble.setText("2.75");
        }
if(en==75||en==76){
     lble.setText("3.00");
        }
if(en==75||en==74||en==73||en==72||en==71||en==70||en==69||en==68||ma==67||en==66||en==65||en==64||en==63||en==62||en==61||en==60||en==59){
    lble.setText("5.00");
        }


if(et==98||et==99||et==100){
    lblet.setText("1.00");
        }
if(et==95||et==96||et==97){
    lblet.setText("1.25");
        }
if(et==92||et==93||et==94){
    lblet.setText("1.50");
       }
if(et==89||et==90||et==91){
    lblet.setText("1.75");
        }
if(et==86||et==87||et==88){
    lblet.setText("2.00");
        }
if(et==86||et==85){
    lblet.setText("2.25");
        }
if(et==80||et==82){
    lblet.setText("2.50");
        }
if(et==77||et==78||et==79){
    lblet.setText("2.75");
        }
if(et==75||et==76){
     lblet.setText("3.00");
        }
if(et==75||et==74||et==73||et==72||et==71||et==70||et==69||et==68||et==67||et==66||et==65||et==64||et==63||et==62||et==61||et==60||et==59){
    lblet.setText("5.00");
        }
        
     }catch(Exception e){
         JOptionPane.showMessageDialog(null, "Student Name Not Found");
     }

    }//GEN-LAST:event_jButton2ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MFRM().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cmb;
    private javax.swing.JTextField e1;
    private javax.swing.JTextField e10;
    private javax.swing.JTextField e2;
    private javax.swing.JTextField e3;
    private javax.swing.JTextField e4;
    private javax.swing.JTextField e5;
    private javax.swing.JTextField e6;
    private javax.swing.JTextField e7;
    private javax.swing.JTextField e8;
    private javax.swing.JTextField e9;
    private javax.swing.JTextField et1;
    private javax.swing.JTextField et10;
    private javax.swing.JTextField et2;
    private javax.swing.JTextField et3;
    private javax.swing.JTextField et4;
    private javax.swing.JTextField et5;
    private javax.swing.JTextField et6;
    private javax.swing.JTextField et7;
    private javax.swing.JTextField et8;
    private javax.swing.JTextField et9;
    private javax.swing.JTextField j1;
    private javax.swing.JTextField j10;
    private javax.swing.JTextField j2;
    private javax.swing.JTextField j3;
    private javax.swing.JTextField j4;
    private javax.swing.JTextField j5;
    private javax.swing.JTextField j6;
    private javax.swing.JTextField j7;
    private javax.swing.JTextField j8;
    private javax.swing.JTextField j9;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel140;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel lble;
    private javax.swing.JLabel lblet;
    private javax.swing.JLabel lblj;
    private javax.swing.JLabel lblm;
    private javax.swing.JLabel lbln;
    private javax.swing.JTextField m1;
    private javax.swing.JTextField m10;
    private javax.swing.JTextField m2;
    private javax.swing.JTextField m3;
    private javax.swing.JTextField m4;
    private javax.swing.JTextField m5;
    private javax.swing.JTextField m6;
    private javax.swing.JTextField m7;
    private javax.swing.JTextField m8;
    private javax.swing.JTextField m9;
    private javax.swing.JTextField n1;
    private javax.swing.JTextField n10;
    private javax.swing.JTextField n2;
    private javax.swing.JTextField n3;
    private javax.swing.JTextField n4;
    private javax.swing.JTextField n5;
    private javax.swing.JTextField n6;
    private javax.swing.JTextField n7;
    private javax.swing.JTextField n8;
    private javax.swing.JTextField n9;
    private javax.swing.JTextField srch;
    // End of variables declaration//GEN-END:variables

}
